// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFmzsEeC3VI9hcy3Ygp1xUEtGn9-MtrLo',
    appId: '1:584756386654:web:1caaa108646a665b554dcf',
    messagingSenderId: '584756386654',
    projectId: 'goornot-108fa',
    authDomain: 'goornot-108fa.firebaseapp.com',
    storageBucket: 'goornot-108fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRfN8z77kF3FOXwRoWnFP3V7CNC6amTHs',
    appId: '1:584756386654:android:3e65fa886251b4dc554dcf',
    messagingSenderId: '584756386654',
    projectId: 'goornot-108fa',
    storageBucket: 'goornot-108fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHj7SpvXMaXd3z0PSNMhCdh2UWG8scOmI',
    appId: '1:584756386654:ios:58655aed3cdcf24b554dcf',
    messagingSenderId: '584756386654',
    projectId: 'goornot-108fa',
    storageBucket: 'goornot-108fa.firebasestorage.app',
    iosBundleId: 'com.example.goornot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHj7SpvXMaXd3z0PSNMhCdh2UWG8scOmI',
    appId: '1:584756386654:ios:58655aed3cdcf24b554dcf',
    messagingSenderId: '584756386654',
    projectId: 'goornot-108fa',
    storageBucket: 'goornot-108fa.firebasestorage.app',
    iosBundleId: 'com.example.goornot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFmzsEeC3VI9hcy3Ygp1xUEtGn9-MtrLo',
    appId: '1:584756386654:web:d670085b65e8e44a554dcf',
    messagingSenderId: '584756386654',
    projectId: 'goornot-108fa',
    authDomain: 'goornot-108fa.firebaseapp.com',
    storageBucket: 'goornot-108fa.firebasestorage.app',
  );
}
